import{a as S,S as v,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="50326285-e5938c14f2b0dcc6b2d24cfe3",B="https://pixabay.com/api/";async function u(r,t){const n={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(B,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".load-more"),h=document.querySelector(".loader"),$=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:w})=>`<a href="${s}" class="photo-card">
          <img src="${n}" alt="${e}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${a}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${w}</p>
          </div>
        </a>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){f.innerHTML=""}function p(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function O(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}const A=document.querySelector(".search-form");let i="",l=1,d=0;A.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.target.elements.searchQuery.value.trim(),l=1,M(),b(),!!i){p();try{const t=await u(i,l);if(d=t.totalHits,t.hits.length===0){c.info({message:"No images found. Try again!"});return}y(t.hits),d>15&&O()}catch{c.error({message:"Something went wrong!"})}finally{g()}}});document.querySelector(".load-more").addEventListener("click",async()=>{l+=1,p();try{const r=await u(i,l);y(r.hits);const t=document.querySelector(".gallery a").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery a").length>=d&&(b(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Something went wrong!"})}finally{g()}});
//# sourceMappingURL=index.js.map
